language: generic

script:
  - source pr_tag_release.sh

deploy:
  provider: releases
  api_key:
    secure: T739Vg/yQQ5CP34WKmxlS4QY0ZOi/w80IsATKS0e3qgNxWjYngQmJrGij3/wo0+yoWLLp9oSKgvuJnLGw98FFVaVq4iB1415rO2k1DGyHJzef7DWOs/DlBopGEi0N0Sbdz6z1tRZ8x3MszEtL9YU3mEixQ41uN68zGuw0pYEY754AhLLP9fZDuXESyiHevEf0zPn/ZbX2qVbjcGcVNllo615xhYnVdPWtmnTC9ytf6colQ/L7kSxR0f0HpU9G27ccI6XbaS4gHNMuT7VyXc1mkcbgj8xQCQHOH58B72q+p2JAjPZDXyNuxrOnq/xvubZ1Z0u+yKDPKNCSbW9pKOLvgXigw0TH3uU84ZR99WE4O2NgmRVPPiCAYM2hzqyGjfijKHVuJBkz1SKl1zaG5KZhzU7176zHbB7IFrWIiF2ArMd+giR5ZwF8w7QqjmeBMw58AdhQaBxTjsgdmUugMP3Yp1kuxavTKi8OcgI+XmYsdGVuC6tOsz4f9u438Yr9vEs7liXgrModJiqKwYK9g8LpGVTH3vm5oAu1YXM1Q6wBf4kuH/rnxNmC+lH+03j6CbmdMqC8Y0YhCP5iDnrjSx87FdGzh5e2BjpkF31YTbuRgp1Tn+nMXiTFyz18XJ1qA14vpLLql6OgT5diOyOExN5k9QQrvF458/UJSGtgoDX//I=
  file: pr_tag_release.sh
  on:
    tags: true
